name: Java docker application
on:
  push:
    branches: [ "master" ]
    paths:
      - apps/java/**

permissions:
  contents: read
  packages: write
  id-token: write
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }} 
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:  apps/java/
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          docker build -t ghcr.io/cifuab/java .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        id: build-and-push
        run: docker push ghcr.io/cifuab/php:latest
      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: |
      #       user/app:latest
      #       user/app:1.0.0
      #       ghcr.io/user/app:latest
      #       ghcr.io/user/app:1.0.0


      # - name: helm deploy
      #   id: deploy-eks 
      #   #directory  example\apps\charts readme inside
      #   run: helm install -f ..\java\hello-world\values.yaml java ./